name: Auto-merge Owner only

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'jge162' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
    
      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL" 
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.WORKFLOW_SECRET}}
